# Generated by Django 3.1.2 on 2021-10-17 06:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import text_reader.apps.textreader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, help_text='Short description of the document.', max_length=100, null=True, verbose_name='Document description')),
                ('document_file', models.FileField(help_text='Upload document for parsing and text reader.', upload_to=text_reader.apps.textreader.models.document_file_path, validators=[text_reader.apps.textreader.models.validate_document], verbose_name='Document for text reader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
